//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balances
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string MaterialName { get; set; }
        public int LifeTime { get; set; }
        public int Expired { get; set; }
        public string ImageUrl { get; set; }
        public string Department { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> CategoryId { get; set; }
    }
}
